apply = "//*[@content-desc='Применить']"
date_picker_time = "//*[@content-desc='Время оплаты']"
date_picker_period =  "//*[@content-desc='Интервал']"
date_picker_week = "//*[@content-desc='Каждую неделю']"
date_picker_month = "//*[@content-desc='Каждый месяц']"
date_picker_myperiod = "//*[@content-desc='Мой период']"
button_save = "//*[@content-desc='Сохранить']"
button_continue = "//*[@content-desc='Продолжить']"
date_picker_date = "//*[@content-desc='Выберите дату']"
edit_button = "//*[@content-desc='Редактировать']"
